name: Create JSON file

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create JSON file
      run: |
        python -c "import json; data = [line.rstrip() for line in open('list.txt')]; with open('list_file.json', 'w') as f: json.dump(data, f)"
