name: Create Known Extension text file

on:
  workflow_dispatch

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: python create_known_ext_list.py
