name: Create CSV file

on:
  workflow_dispatch

#on:
#  push:
#    paths:
#      - 'list.txt'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install package
      run: python -m pip install selenium
    - name: Run script
      run: python RansomNameToExten.py
    - name: Commit files
      run: |
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name ${{ github.actor }}
        git add ./ExtensionWithRansomName.csv
        git commit -m "Updated the ExtensionWithRansomName.csv file"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
